before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  -
    id: "notecard-linux"
    dir: notecard
    binary: notecard

    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64

  -
    id: "notehub-linux"
    dir: notehub
    binary: notehub

    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
  -
    id: "notecard"
    dir: notecard
    binary: notecard

    env:
      - CGO_ENABLED=1
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm64

  -
    id: "notehub"
    dir: notehub
    binary: notehub

    env:
      - CGO_ENABLED=1
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm64

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    id: notecard_deb
    package_name: notecard
    builds:
     - notecard-linux
    vendor: Blues
    homepage: https://blues.com
    maintainer: Blues <blues@blues.com>
    description: Notecard CLI
    license: MIT
    formats:
      - deb

  -
    id: notehub_deb
    package_name: notehub
    builds:
     - notehub-linux
    vendor: Blues
    homepage: https://blues.com
    maintainer: Blues <blues@blues.com>
    description: Notehub CLI
    license: MIT
    formats:
      - deb

brews:
  - repository:
      owner: blues
      name: homebrew-note-cli
    directory: Formula
    homepage: https://blues.com
    description: Note CLI
    license: MIT
