// Copyright 2025 Blues Inc.  All rights reserved.
// Use of this source code is governed by licenses granted by the
// copyright holder including that found in the LICENSE file.

package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// docsCmd represents the docs command
var docsCmd = &cobra.Command{
	Use:    "docs",
	Short:  "Generate CLI documentation",
	Long:   `Generate Markdown documentation for all CLI commands.`,
	Hidden: true,
	RunE: func(cmd *cobra.Command, args []string) error {
		outputDir, _ := cmd.Flags().GetString("output")

		// Resolve to absolute path
		absDir, err := filepath.Abs(outputDir)
		if err != nil {
			return fmt.Errorf("failed to resolve output path: %w", err)
		}

		// Create output directory
		if err := os.MkdirAll(absDir, 0755); err != nil {
			return fmt.Errorf("failed to create output directory: %w", err)
		}

		// Disable the auto-generated "Auto generated by spf13/cobra" date line
		rootCmd.DisableAutoGenTag = true

		if err := doc.GenMarkdownTree(rootCmd, absDir); err != nil {
			return fmt.Errorf("failed to generate docs: %w", err)
		}

		cmd.Printf("Documentation generated in %s\n", absDir)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(docsCmd)

	docsCmd.Flags().StringP("output", "o", "./doc/cli", "Output directory for generated documentation")
}
