name: audit

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      -
        name: Verify dependencies
        run: go mod verify

      -
        name: Build
        run: go build -v ./...

      -
        name: Run go vet
        run: go vet ./...
